[build]
  # Base directory for the build
  base = "frontend"
  
  # Build command
  command = "npm run build"
  
  # Netlify automatically detects Next.js and handles the publish directory

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Production environment
  NODE_ENV = "production"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
