#!/usr/bin/env node

// Environment Setup Script
// Helps users configure their environment variables correctly

const fs = require('fs')
const path = require('path')
const readline = require('readline')

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
})

const envPath = path.join(process.cwd(), '.env.local')
const examplePath = path.join(process.cwd(), '.env.example')

console.log('🎌 WeAnime Environment Setup')
console.log('============================\n')

async function question(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, resolve)
  })
}

async function setupEnvironment() {
  try {
    // Check if .env.local already exists
    if (fs.existsSync(envPath)) {
      const overwrite = await question('⚠️  .env.local already exists. Overwrite? (y/N): ')
      if (overwrite.toLowerCase() !== 'y') {
        console.log('Setup cancelled.')
        process.exit(0)
      }
    }

    console.log('Let\'s set up your environment variables...\n')

    // Required Supabase configuration
    console.log('📊 SUPABASE CONFIGURATION (Required)')
    console.log('Get these from: https://app.supabase.com/project/[your-project]/settings/api')
    const supabaseUrl = await question('Supabase URL: ')
    const supabaseAnonKey = await question('Supabase Anon Key: ')
    const supabaseServiceKey = await question('Supabase Service Role Key (optional): ')

    // Crunchyroll configuration
    console.log('\n🎬 CRUNCHYROLL CONFIGURATION (Critical for real content)')
    console.log('You need a Crunchyroll Premium account for this to work.')
    const setupCrunchyroll = await question('Set up Crunchyroll integration? (Y/n): ')
    
    let crunchyrollEmail = ''
    let crunchyrollPassword = ''
    let crunchyrollLocale = 'en-US'
    
    if (setupCrunchyroll.toLowerCase() !== 'n') {
      crunchyrollEmail = await question('Crunchyroll Email: ')
      crunchyrollPassword = await question('Crunchyroll Password: ')
      crunchyrollLocale = await question('Crunchyroll Locale (en-US): ') || 'en-US'
    }

    // Backend configuration
    console.log('\n🔧 BACKEND CONFIGURATION')
    const backendUrl = await question('WeAnime Backend URL (http://localhost:8000): ') || 'http://localhost:8000'
    const fallbackUrls = await question('Fallback Backend URLs (comma-separated, optional): ')

    // Optional APIs
    console.log('\n🌐 OPTIONAL API CONFIGURATION')
    const youtubeApiKey = await question('YouTube API Key (for trailers, optional): ')

    // Feature flags
    console.log('\n🚀 FEATURE CONFIGURATION')
    const enableRealStreaming = await question('Enable real streaming (Y/n): ')
    const enableAuth = await question('Enable user authentication (Y/n): ')

    // Generate .env.local content
    const envContent = generateEnvContent({
      supabaseUrl,
      supabaseAnonKey,
      supabaseServiceKey,
      crunchyrollEmail,
      crunchyrollPassword,
      crunchyrollLocale,
      backendUrl,
      fallbackUrls,
      youtubeApiKey,
      enableRealStreaming: enableRealStreaming.toLowerCase() !== 'n',
      enableAuth: enableAuth.toLowerCase() !== 'n'
    })

    // Write .env.local file
    fs.writeFileSync(envPath, envContent)

    console.log('\n✅ Environment configuration saved to .env.local')
    console.log('\n📋 NEXT STEPS:')
    console.log('1. Review your .env.local file')
    console.log('2. Start the Crunchyroll bridge: cd crunchyroll-bridge && cargo run')
    console.log('3. Start your development server: npm run dev')
    console.log('4. Test the configuration: npm run test:env')
    
    if (crunchyrollEmail) {
      console.log('\n🎬 CRUNCHYROLL SETUP:')
      console.log('- Make sure your Crunchyroll account has an active premium subscription')
      console.log('- Test the bridge with: cd crunchyroll-bridge && cargo run -- login --email ' + crunchyrollEmail + ' --password [password]')
    }

    console.log('\n⚠️  SECURITY REMINDER:')
    console.log('- Never commit .env.local to version control')
    console.log('- Use strong passwords and rotate credentials regularly')
    console.log('- Keep your API keys secure')

  } catch (error) {
    console.error('❌ Setup failed:', error.message)
    process.exit(1)
  } finally {
    rl.close()
  }
}

function generateEnvContent(config) {
  return `# WeAnime Environment Configuration
# Generated by setup script on ${new Date().toISOString()}

# =============================================================================
# SUPABASE CONFIGURATION
# =============================================================================
NEXT_PUBLIC_SUPABASE_URL=${config.supabaseUrl}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${config.supabaseAnonKey}
${config.supabaseServiceKey ? `SUPABASE_SERVICE_ROLE_KEY=${config.supabaseServiceKey}` : '# SUPABASE_SERVICE_ROLE_KEY=your_service_role_key'}

# =============================================================================
# CRUNCHYROLL INTEGRATION
# =============================================================================
${config.crunchyrollEmail ? `CRUNCHYROLL_EMAIL=${config.crunchyrollEmail}` : '# CRUNCHYROLL_EMAIL=your_email@example.com'}
${config.crunchyrollPassword ? `CRUNCHYROLL_PASSWORD=${config.crunchyrollPassword}` : '# CRUNCHYROLL_PASSWORD=your_password'}
CRUNCHYROLL_LOCALE=${config.crunchyrollLocale}
CRUNCHYROLL_BRIDGE_URL=http://localhost:8080

# =============================================================================
# BACKEND CONFIGURATION
# =============================================================================
NEXT_PUBLIC_BACKEND_URL=${config.backendUrl}
WEANIME_BACKEND_URL=${config.backendUrl}
${config.fallbackUrls ? `WEANIME_BACKEND_FALLBACK_URLS=${config.fallbackUrls}` : '# WEANIME_BACKEND_FALLBACK_URLS=http://localhost:8001,http://localhost:8002'}

# =============================================================================
# EXTERNAL APIS
# =============================================================================
JIKAN_API_URL=https://api.jikan.moe/v4
KITSU_API_URL=https://kitsu.io/api/edge
ANILIST_API_URL=https://graphql.anilist.co
${config.youtubeApiKey ? `YOUTUBE_API_KEY=${config.youtubeApiKey}` : '# YOUTUBE_API_KEY=your_youtube_api_key'}

# =============================================================================
# FEATURE FLAGS
# =============================================================================
FEATURE_REAL_STREAMING_ENABLED=${config.enableRealStreaming}
FEATURE_AUTH_ENABLED=${config.enableAuth}
FEATURE_CRUNCHYROLL_ENABLED=${!!config.crunchyrollEmail}

# =============================================================================
# DEVELOPMENT CONFIGURATION
# =============================================================================
NODE_ENV=development
DEBUG=true
VERBOSE_API_LOGGING=true

# =============================================================================
# RATE LIMITING
# =============================================================================
API_RATE_LIMIT_ENABLED=true
API_RATE_LIMIT_REQUESTS=100
API_RATE_LIMIT_WINDOW=60

# =============================================================================
# CACHING
# =============================================================================
CACHE_TTL=300
# REDIS_URL=redis://localhost:6379

# =============================================================================
# SECURITY
# =============================================================================
JWT_SECRET=${generateRandomString(32)}
NEXTAUTH_SECRET=${generateRandomString(32)}
NEXTAUTH_URL=http://localhost:3000
`
}

function generateRandomString(length) {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'
  let result = ''
  for (let i = 0; i < length; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length))
  }
  return result
}

// Run the setup
setupEnvironment().catch(console.error)
